site_name: ${{values.app_name}}
site_description: Main documentation for ${{values.app_name}}
repo_url: https://github.com/vinaysingh19/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Home: index.md